name: Deploy to EC2 Server

on:
  push:
    branches:
      - main  # Trigger when pushing to 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
 

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.key}}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.host }} >> ~/.ssh/known_hosts
      
      - name: Deploy Code to EC2
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.user }}@${{ secrets.host }} << 'EOF'
            cd /home/ec2-user/myapp   
            git pull origin main      
            npm install               
            pm2 restart all           
          EOF
      
